version: "3.8"

services:
    php:
      container_name: php
      build:
        context: ./front
        dockerfile: dockerfile_php
      ports:
        - '9000:9000'
      volumes:
        - ./front:/var/www/html

    nginx:
      container_name: nginx
      image: nginx:stable-alpine
      ports:
        - '8080:80'
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./front:/var/www/html
      depends_on:
        - php
